### PR TITLE
fix #40 allow ?thanks without for and/or without message

### LINKED ISSUE #40: Improve ?thanks command
I see the `?thanks` command quite often being used without a `for`. The bot responds that the message could not be parsed (_You have to use the word "for" when thanking someone. For example: ?thanks @​user for being so nice and answering my questions_), but I believe that this experience can be improved. 

I see two variants in which people fail:

1. Missing the word `for`.
    
    ```
   ?thanks @user you did something awesome
    ```
    
    I think this could just be accepted as a valid thank you without to much hassle? 

2. No message at all. 
    
    ```
    ?thanks @user
    ```
    
    I think this could still be treated as a valid "thank you". The bot could just fall back to a more neutral message. Something like "_you got thanked 🎉! @​someone appreciates you!_". Leaving out the quote.

### PR DESCRIPTION
**Pull request by Aprillion**
**What**: fixing #40 by allowing ?thanks command without `for` and/or without message

**Why**: 

**How**:

**Checklist**:

- [ ] Documentation N/A
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

File: src/commands/command-fns/thanks.js [hunk 1]
```diff
@@ -55,25 +55,9 @@ async function sayThankYou(args, message, thanksHistory) {
...
-  const example = `For example: \`?thanks ${thankedMembersListString} for being so nice and answering my questions\``
-  if (!args.includes(' for ')) {
-    return message.channel.send(
-      `You have to use the word "for" when thanking someone. ${example}`,
-    )
-  }
 
-  const thanksMessage = args
-    .replace(MessageMentions.USERS_PATTERN, '')
-    .replace(/^.*?for/, '')
```
Comment (Aprillion) [inline src/commands/command-fns/thanks.js:70]: FTR: MessageMentions.USERS_PATTERN is `/<@!?(\d{17,19})>/g` => it did not do any replacement itself, all was done by the second regexp `/^.*?for/` in the deleted code

(at least in the unit tests, I don't have any test Discord server to try it manually...)

File: src/commands/command-fns/__tests__/thanks.js [hunk 2]
```diff
@@ -101,6 +101,86 @@ Link: <${thanksMessage}>
...
+    .toMatchInlineSnapshot(`
+    "Hey <@123>! You got thanked! 🎉
+
+    <@123> appreciated you for:
+
+    > 👍
+
+    Link: <https://discordapp.com/channels/123/123/123>"
+  `)
+})
```
Comment (marcosvega91) [inline src/commands/command-fns/__tests__/thanks.js]: I think that when there is no message we can simply say 

```
Hey <@123>! You got thanked by <@123>! 🎉
Link: <https://discordapp.com/channels/123/123/123>
```

what do you think?

File: src/commands/command-fns/thanks.js (hunk 1 above)
Comment (marcosvega91) [reply src/commands/command-fns/thanks.js:70]: When you mention someone the message will contain something similar to `<@1233435454546563>`.

Your regex will work but I prefer what we already have. 

1. `.replace(MessageMentions.USERS_PATTERN, '')` will remove the mentioned user
2. `.replace(/^.*?for/, '')` will remove the text before `for` if is present.

**Review by marcosvega91 — CHANGES_REQUESTED** [review]
Hi @Aprillion thanks for working on this :). It's awesome :). I have left two small comments, let me know what you think

File: src/commands/command-fns/__tests__/thanks.js (hunk 2 above)
Comment (Aprillion) [reply src/commands/command-fns/__tests__/thanks.js]: That sounds reasonable, not sure when I will find time to dig into that part of code deeper. Maybe today or next week.

File: src/commands/command-fns/thanks.js (hunk 1 above)
Comment (Aprillion) [reply src/commands/command-fns/thanks.js:70]: Could you please update the unit tests so they reflect the situation you are describing?

Since the regex did not match in the test, I have no idea what exactly do you mean :(

e.g. `await setup('?thanks @user1 for the help with epicReact', ['user1'])` does not contain `<@1233435454546563>` so the regex 1. is a no-op and regex 2. is doing all the work in that test case as far as I can tell

File: src/commands/command-fns/__tests__/thanks.js (hunk 2 above)
Comment (smeijer) [reply src/commands/command-fns/__tests__/thanks.js]: @marcosvega91 , what do you think about this one in case a `for` is present:

(current state)
```
    Hey <@123>! You got thanked! 🎉

    <@123> appreciated you for:

    > 👍

    Link: <https://discordapp.com/channels/123/123/123>
```

And this one for when there is no `for`:

```
    Hey <@123>! You got thanked! 🎉

    <@123> appreciates you.

    Link: <https://discordapp.com/channels/123/123/123>
```

I think it shows a bit more gratitude than your variant.

Comment (Aprillion) [reply src/commands/command-fns/__tests__/thanks.js]: now fixed, using Stephan's suggestion.

Comment (marcosvega91) [reply src/commands/command-fns/__tests__/thanks.js]: yes I like his suggestion, thanks guys

File: src/commands/command-fns/thanks.js (hunk 1 above)
Comment (marcosvega91) [reply src/commands/command-fns/thanks.js:70]: Yes I understand what you mean. The problem here is that the `discord` client will replace the `@user1` with `<@1233435454546563>` where `1233435454546563` is the user id. If you look at the `private-chat` test file  I have built the content dynamically in the setup function

https://github.com/kentcdodds/kcd-discord-bot/blob/e18b7a13b9abf1e814df98feb019531db4eaf3b6/src/commands/command-fns/__tests__/private-chat.js#L23-L30

I think that we can update the `setup` of `thanks` test as

```js
async function setup(content, mentionedUsernames = []) {
  const {client, defaultChannels, kody, createUser} = await makeFakeClient()
  const mentionedUsers = (
    await Promise.all(mentionedUsernames.map(username => createUser(username)))
  ).map(guildMember => guildMember.user)

  const message = new Discord.Message(
    client,
    {
      id: SnowflakeUtil.generate(),
      content: content.replace(/\@(\S+)/, (_, mention) =>
        mentionedUsers.find(user => user.username === mention),
      ),
      author: kody.user,
    },
    defaultChannels.talkToBotsChannel,
  )

  Object.assign(message, {
    mentions: new Discord.MessageMentions(message, mentionedUsers, [], false),
  })

  const getBotMessages = () =>
    Array.from(defaultChannels.talkToBotsChannel.messages.cache.values())
  const getThanksMessages = () =>
    Array.from(defaultChannels.thanksChannel.messages.cache.values())
  return {
    getBotMessages,
    getThanksMessages,
    mentionedUsers,
    kody,
    botChannel: defaultChannels.talkToBotsChannel,
    thanksChannel: defaultChannels.thanksChannel,
    message,
    createUser,
  }
}
```

Comment (Aprillion) [reply src/commands/command-fns/thanks.js:70]: perfect, thanks for the setup function!

PR updated, so `MessageMentions.USERS_PATTERN` is back => diff can be found in the latest [force-pushed](https://github.com/kentcdodds/kcd-discord-bot/compare/09fe25a6cf7aa2d2334a8265d9096aba4771e6ac..906dee2ff9080a4c58bd35ed8991ab6b4eb3be58) link if you want to see just the last change.

**Review by marcosvega91 — APPROVED** [review]
For me is nice :) thanks @Aprillion

**Review by kentcdodds — APPROVED** [review]
Super! Thank you 👏👏

**Comment by kentcdodds** [comment]
@all-contributors please add @Aprillion for code and tests
